@startuml



package business_layer {
    class TuringMachineController {
        - machines: Dictionary<string, TuringMachine>

        + add(name: string, machine: TuringMachine): void
        + remove(name: string): void
        + get(name: string): TuringMachine
        + get_all_names(): Iterable<string>
        + run(turing_machine_name:string,input:string):configuration
        +visualize(Turing_machine_name:string, input:string):void
        +validate(Turing_machine_name:string,function_obj,extreme_case:list<string>,test_count:int,max_input_length:int):boolean

    }


 class CombinedTuringMachine <<immutable dataclass>> {
        -turing_machines: list<string>
        +run() : configuration
        + states: FrozenSet<State>
        + input_alphabet: Alphabet
        + tape_alphabet: Alphabet
        + blank_character: Letter
        + delta: TransitionTable
        + accepting_state: State
        + rejecting_state: State
        + initial_state: State

    }


     class TuringMachineVisualizer <<immutable dataclass>> {
        -turing_machine: TuringMachine | CombinedTuringMachine
        -steps : list<configuration>
        -add_step(tuple(tape,head_position,current_state)) : void
        +build_steps():void
        -build_steps_turingmachine(): void
        -build_steps_turingmachinecombined(): void
        +get_steps():list<configuration>
    }

    class Configuration <<immutable dataclass>> {
       -tape :Tape
       -head_position:int
       -state:State
    }

       class State <<immutable dataclass>> {
        -state:string
    }

      class Tape <<immutable dataclass>> {
        -tape_symbols:list<string>
    }

    class TuringMachine <<immutable dataclass>> {
        + states: FrozenSet<State>
        + input_alphabet: Alphabet
        + tape_alphabet: Alphabet
        + blank_character: Letter
        + delta: TransitionTable
        + accepting_state: State
        + rejecting_state: State
        + initial_state: State
        +run(input_string:string):configuration
        +run_step(configuration):configuration
        +contains_chars(input_string:string, input_alphabet:list<char>):boolean
        +run_combined(input_string:string,head_position:int):configuration

    }

    class TuringMachineRun {
       - machine: TuringMachine
       - input: Word
       - config: configuration
       - history: Stack<Undo>

       + get_result(): TuringMachineResult
       + reset(): void
       + step(): void
       + undo(): void
       + run_multiple_steps(): void
    }



package testing {
    abstract class TuringMachineTester {

    }

    class ConstantWordsTester {

    }

    class RandomizedTester {

    }

    ConstantWordsTester -u-|> TuringMachineTester
    RandomizedTester -u-|> TuringMachineTester

    }
}


package service_layer {

}

package presentation_layer {

}

service_layer -d-> bussiness
presentation_layer -d-> service_layer

@enduml